language: node_js
node_js:
- '6'
before_script:
- cp server/config/config-example.js server/config/config.js
- mysql -u travis < db/schema.sql
script:
- npm start &
- npm test
deploy:
  provider: heroku
  api_key:
    secure: mv207ZXBveFNi2iZecgb7wIocPZa04hlFdN8yVZcdmX0YEIOpQlgjrackoshWDmB3px3LlCqT2ewgRfqw4gIiPOvNhCplVpGVW27s/78iECFML4qPdP6Wm4iK/fKORfdgJIHM69wEB0Kr3/9ClRR0LcJx0OaCnw4NcxNWoz5BhdxHOFRfCd54QoyE1xYps//EoI1kCaImGGSnAQeEiG4VL9yq+ZJT8j9SiU6P+UTf5FbSao41q7rV+RvE4/aoH5ggDUhTkGnx6dvE/8Hbl91En8LeRP6sqYBHzvE84cg+ByUe8tUGSzJ+lC1UFkRyS9jE9Gju4IwF8+NS+hZKGy/kom2jnt93y4mZjSO7QFYyRqo0FEAOYt9aI3J6WYVY0OPHY34HMS7RCRimYp4RCUMU5m12Qg1XXydH5P+dc9XOz01ka4U/ZKV4hy+8w5Wv2lR8wl7bFA1LhoR2SQyVratA8mJV2wGqaPoubHwZDmb+WX58MBPcdphvciY81E9P3K/BHIkiaxlOSg9VaY5wyD+I6eXR3vk9TXnN+MvbUaWZ0zwKaeRoWsGAcjz9d2/KrXBUahVBqYzlYDAzWd1jgtRG2/TXS8WPwLEhxqywtTgaqd+SElWiA/Yn14ZW1RjAfHv0/PTeb43dYM89YMdP6awLrPvaognSGhb0dBEAdKuHgE=
  app: react-ion
