language: node_js
node_js:
- '6'
before_script:
- mysql -u travis < db/schema.sql
script:
- npm start &
- npm test
deploy:
  provider: heroku
  api_key:
    secure: l0tobrMYb2gqxDWd3YOW8Yan3bJXcLaF/ZYvG4wS/FyuM0gmgOmPzXdnOQE884FnSoc3/0CcU+L9gGs2/y2VSeRTRszrY6we03YcUf4qrFVkPadnZXUit+ReX53Vl3YG8EzUOQRlmOFTRi4xc1hyPVBI1FjkaJjVVwgngdXWWa/8d+2GTulUfqHvMmCMCK/e6MVP6MgSQ8cwDoxch2sSbiXIDTkM+CGLjoKmQb3cKGtbz97H0QUP4FPlCGaGykG95VzbmpwW8a2f6FwQ6eHCS0WKni9DE+yITXlWhwjDggP+IGrI4f8+Bborskm+2AeEZsRpx0xiFfEle24qtKg2V4hKg52EEoVy5TdvI9XyiCjH3UzIpgGsQAMDhiU3j5GQ2iCUuGmKwb246/XZNhpOZ3gzp0eJ/TWr43OsD8MnehWZ/KI4JWysdqZQLZGdVG/xVnbYhY5VPwl6OB9EICO42oS5AhSO50C9y74ApWOp/2t1LvoQB32DNvtoMdPczwqjGYIVS04KqNzzNKCyUKq5sy5GdM4QslKFP4T+xjeAu7SxO4lwu4GVTM/ZLN39jeqHsnsI+/1zA3ijW0cKbDmQ7lFlaC7zEbFVz0gAVihmj2B41nFDg8533vLD+/eStIv9cgKFiGe0xFD8iIaRiuup09/kQelvYwPjzAgq+JV3qh4=
  app: react-ion-api
  on:
    repo: React-Ion/React-Ion-API
