language: node_js
node_js:
- '6'
before_script:
- mysql -u travis < db/schema.sql
script:
- npm start &
- npm test
deploy:
  provider: heroku
  api_key:
    secure: WE7dzKU/dw6uhkgXyqMPO9Tf30BabEl9/dZTxc5YVIN7gJMwTpQAu/gRoPQJq+SoHhbh+FN1d7gtjzgGXelY8WpuBVVb8Ufn0AQp3TTGKtb8Q9DTXeBOBT+lDAbJOlGfNTmDNEPaDieO2HH6MwOoU5tj8L0smwdO2q5rrzIaV7umYxxN/diZLx2m7sJj51fbrEFoorSAW2kgLJ0R1EwU7XbniVMTM4LHfddbzOCWO1ZRkupu+Tqs+aDE/V+Zf7LLuglqL7mGPB2xFFKy0jxQ5ARuzdQhWrU0WlFmOqfoRKteWQZd2XBGflRKSP1yMd8IyVHJxFc6OqP5XmY8HSvny2MBUByn9GB/oHoragtR77gTjk3B/k7GIXqGrlGP19aUsrR0PbokvPbEpFVcc0mCjo8BhVSE7wHlQRdM28V0ef75AyXjbRBDFwmLITwY2ondckji/gZ9YZs2uBXBbQOkxJdePBikCuO36/K01OTw0QZR+7M29hoqnnN9k42B3MBtLiSXYtQRL8u+Mc+jTQHsCgl7JRkwDCTE0BtSdU3ciqA5qYDV1N/uBYD0xXMoukM2QAwhM1zshTX4w1/Mmfo2LvmOhLgHbVhNMdKUEHc9hnRt/MLEgiu0NN7nsgcn6SyiPDjk5Cy5FSwk1qTbpg/OcguYeMX0DWmUsxMf4bqfHGI=
  app: react-ion-api
  on:
    repo: React-Ion/React-Ion-API
